import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const nexonGothic = localFont({
  src: "../assets/fonts/NEXONLv1GothicLowOTF.otf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout : 전체 뼈대
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`antialiased ${nexonGothic.className}`}>{children}</body>
    </html>
  );
}
